// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO0JL8_WmuRwnIbSXj0N8Oy7wAQPVULI8',
    appId: '1:652484007316:web:58816a14addb3c8c3e6b81',
    messagingSenderId: '652484007316',
    projectId: 'chatsphere-25f96',
    authDomain: 'chatsphere-25f96.firebaseapp.com',
    storageBucket: 'chatsphere-25f96.firebasestorage.app',
    measurementId: 'G-LDTPPBB7DN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZA0JUIBn0X46WAnXk50xMoOvNBD3vtEg',
    appId: '1:652484007316:android:3f58b6c9ac369bfe3e6b81',
    messagingSenderId: '652484007316',
    projectId: 'chatsphere-25f96',
    storageBucket: 'chatsphere-25f96.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqgk5QRWRmY3_NKp1PNeTBGFJTYEJ_g0k',
    appId: '1:652484007316:ios:30667d3b03c0403e3e6b81',
    messagingSenderId: '652484007316',
    projectId: 'chatsphere-25f96',
    storageBucket: 'chatsphere-25f96.firebasestorage.app',
    iosBundleId: 'com.example.chatSphere',
  );
}
